### ISSUE TITLE
Wrong getter and setter function name

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/socialfield#28]
I was searching my code and saw this. I don't have steps to reproduce anything but noticed that these getter and setter function names are wrong:

 - `entity_metadata_field_verbatim_get` should be `entity_plus_metadata_field_verbatim_get`
 - `entity_metadata_field_verbatim_set` should be `entity_plus_metadata_field_verbatim_set`

Reference: https://github.com/backdrop-contrib/entity_plus/issues/33#issuecomment-984298911

**Comment by laryn** [comment]
~That would also mean a dependency on Entity Plus.~

**Comment by argiepiano** [comment]
The fix is correct, but there is no need to depend on Entity Plus. The way it works:
- IF Entity Plus is enabled, then the  property_callback for the field in socialfield_field_info() is used
- If Entity Plus is not enabled, then the property_callback is simply ignored. Meaning that `socialfield_property_callback_property_info_callback` will never be called, and the setter/getter will never be used

Enabling Entity Plus would allow someone to use entity metadata wrappers to set the field values. But this is not required for the module to function.

**Comment by argiepiano** [comment]
To clarify, this change should be done, but there is no need to depend on E+

**Comment by laryn** [comment]
Thanks @argiepiano!

**Comment by jenlampton** [comment]
Fixed in `8565f1e`, thank you both!
